# Generated by Django 4.1.7 on 2023-02-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('volume', models.FloatField(verbose_name='Объем в мл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Картинка')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует ли?')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/ingredients/%Y/%m/%d', verbose_name='Картинка')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует ли?')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='recipe_coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='Шаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/recipe/%Y/%m/%d', verbose_name='Картинка')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.coffee', verbose_name='Кофе')),
            ],
            options={
                'verbose_name': 'Рецепт кофе',
                'verbose_name_plural': 'Рецепты кофе',
            },
        ),
        migrations.CreateModel(
            name='ingredient_coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_ingredient', models.FloatField(verbose_name='Кол-во')),
                ('measured', models.CharField(max_length=50, verbose_name='В чем измеряется?')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.coffee', verbose_name='Кофе')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.ingredients', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент кофе',
                'verbose_name_plural': 'Ингредиенты кофе',
                'unique_together': {('coffee', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='coffee',
            name='ingredient',
            field=models.ManyToManyField(through='coffee_house.ingredient_coffee', to='coffee_house.ingredients', verbose_name='Ингредиент'),
        ),
    ]
